message: Test Load...

spring:
  zipkin:
    base-url: http://192.168.1.135:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost:8761}/eureka
