spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/api/orders/**
        filters:
        - RemoveRequestHeader=Cookie
        - name: CircuitBreaker
          args:
            name: ORDER-SERVICE
            fallbackUri: forward:/orderServiceFallback
      - id: BILLING-SERVICE
        uri: lb://BILLING-SERVICE
        predicates:
        - Path=/api/billings/**
        filters:
        - RemoveRequestHeader=Cookie
        - name: CircuitBreaker
          args:
            name: BILLING-SERVICE
            fallbackUri: forward:/billingServiceFallback
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://dell-pc:8777/auth/realms/demo/protocol/openid-connect/token
            authorization-uri: http://dell-pc:8777/auth/realms/demo/protocol/openid-connect/auth
            userinfo-uri: http://dell-pc:8777/auth/realms/demo/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak-with-test-scope:
            provider: keycloak
            client-id: springboot-microservice
            client-secret: 774cfa5e-1277-4c4c-8224-aff51ef43eff
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

