message: ORDER-SERVICE load....

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/training_micro?serverTimezone=UTC
    username: taufik
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/db/master.xml
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://dell-pc:8777/auth/realms/master      

keycloak:
  realm: demo
  auth-server-url: http://dell-pc:8777/auth
  ssl-required: external
  resource: springboot-microservice
  credentials.secret: 774cfa5e-1277-4c4c-8224-aff51ef43eff
  use-resource-role-mappings: true
  bearer-only: true
